name: matchms-docs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pip
  - jupyter-book
  - matplotlib
  - matchms
  - scipy=1.10.1
  - spec2vec
  - matchmsextras